---
# recognizes the empty language
# over the alphabet {a, b}
start: start
accept: accept
reject: reject
transitions:
    - ["start", "a", "reject", "x", "R"]
    - ["start", "b", "reject", "x", "R"]
    - ["start", "_", "reject", "x", "R"]
